version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/shogun-boot"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/shogun-gs-interceptor"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
